server:
  port: 1234
spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dingshaohua.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: '@Dsh742308560'
  redis:
    database: 0
    host: 182.92.120.170
    port: 6379
    password: dshvv
  freemarker:
    enabled: true
    charset: UTF-8
    suffix: .html
    content-type: text/html
    prefer-file-system-access: true
    template-loader-path: classpath:/templates/
  mail: # 配置 SMTP 服务器地址
    host: smtp.qq.com # 发送者邮箱
    username: 869043928@qq.com
    password: jebwbejiiarbbddh # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    port: 587  # 端口号465或587
    default-encoding: UTF-8 # 默认的邮件编码为UTF-8
    properties: # 配置SSL 加密工厂
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
sa-token:
  token-name: satoken # token名称 (同时也是cookie名称)
  timeout: 86400 # token有效期，单位s 默认30天, -1代表永不过期 我这里设置24小时